### ISSUE TITLE
Won't find TiVo on local network

### ISSUE THREAD

**Issue by NBCGLX** [mackworth/cTiVo#399] opened 2019-12-12 01:14 UTC
Computer and TiVo are both connected to the same network. Downloads are enabled on the TiVo. Prior to the latest update, there was no issue. After update, the TiVo can't be found.

**Comment by mackworth** [comment] 2019-12-12 01:19
Sorry to hear that. Can you 
launch cTiVo, holding down the Control and Option keys 
wait about twenty seconds
Use menu Help>Show Logs in Finder
Then come back here and post the log (not via email)
That will show me what cTiVo is being told.

BTW, when you say latest update, do you mean cTiVo or MacOS? Which versions of each are you running?  Which hardware?

**Comment by mackworth** [comment] 2019-12-14 17:33
Any update?

**Comment by esharakan** [comment] 2019-12-17 13:48
Hi, I have the identical problem running cTiVo 3.4.1 on macOS Catalina 10.15.2 on my new MBP 16".  I had to add my two TiVos manually.  This worked fine when I was running cTiVo 3.4.1 on my Mac Mini under Mojave.  Also, I can see my TiVos on my MBP when I run another App that browses my network.

I followed your directions and have attached the log file.
[com.cTiVo.cTiVo 2019-12-17--04-25-50-533.log](https://github.com/mackworth/cTiVo/files/3973532/com.cTiVo.cTiVo.2019-12-17--04-25-50-533.log)

**Comment by mackworth** [comment] 2019-12-17 14:03
So, the log shows both Bedroom and Den are marked as Disabled, meaning that the Enabled check box in Preferences>TiVos>Local Network TiVos is turned off.  Note that if you have an enabled manual one going to the same TiVo, it automatically disables the automatic one, so you'll have to disable the one you created before enabling the other one. (OTOH, both Bedroom and Den look like they were disabled somehow before the manual ones were created.)

On the other hand, I do see the following msgs:
 `2019-12-16 23:53:58:560 -[MTTiVoManager netServiceBrowser:didRemoveService:moreComing:]@1999>Service disappeared: Den
2019-12-16 23:53:58:560 -[MTTiVoManager netServiceBrowser:didRemoveService:moreComing:]@1999>Service disappeared: Bedroom
`
Which suggests that although it is seeing them, they're then dropping off, which is usually due to network issues, such as Wifi interference or other problems.  When you create the manual connection, have you been able to download a show, and do you see significant fluctuations in the throughput?

**Comment by esharakan** [comment] 2019-12-17 14:12
So there are no TiVos listed under Preferences>TiVos>Local Network TiVos to disable.  That's the problem; nothing ever shows up in that window.  And so I added them manually only after they weren't automatically discovered on the local network.  I think you're on to something when you say "both Bedroom and Den look like they were disabled somehow before the manual ones were created".

After adding them manually, downloads are working perfectly fine.  Also, the Mac Mini (where everything works fine) is attached to the same ethernet switch as my laptop, so I don't think there are network issues involved.

**Comment by esharakan** [comment] 2019-12-17 14:14
Okay, things are getting weird.  So I tried to disable the manually added TiVos to see if they might then appear under Local Network TiVos.  They don't , and now I can't re-enqble the ones I manually added.  Clicking the checkbox simply doesn't work!

**Comment by esharakan** [comment] 2019-12-17 14:19
OK, I'm starting over.  I deleted the TiVos I manually added, and ran with control & option keys pressed, and am sending you another log.
[com.cTiVo.cTiVo 2019-12-17--04-25-50-533.log](https://github.com/mackworth/cTiVo/files/3973686/com.cTiVo.cTiVo.2019-12-17--04-25-50-533.log)

**Comment by mackworth** [comment] 2019-12-17 14:28
Definitely weird.  Can you send me your preferences file? (Cmd-Shift-G in Finder then ~/Library/Preferences, and send com.ctivo.ctivo file.)  It has your MAK in it, so you can email directly at mackworth at aol dot com

After you do, that, if you want to try a clean experiment, rename that file to temp.com.ctivo.ctivo, and log out/back in and run cTiVo again.

**Comment by mackworth** [comment] 2019-12-17 14:37
(To be clear, log in/log out means as a Mac user, not cTiVo.  Preferences are cached, so logging out is required to make sure you're not using the old one.  Also, after logging back, in and before running cTivo, make sure there's no com.ctivo.ctivo.plist file for the same reason

**Comment by esharakan** [comment] 2019-12-17 15:31
Prefs file sent separately.  Renaming the prefs file, logging out & back in, and re-running cTiVo made no difference; it still can't find my TiVos.  I did not start cTiVo ith the control & option keys pressed, but there are still messages in the log about disabled TiVos:

2019-12-17 10:28:32:438 -[MTAppDelegate applicationDidFinishLaunching:]@216>Starting cTiVo; version: 1108
2019-12-17 10:28:32:439 -[MTTiVoManager init]@92>LoadTimes: {
}
2019-12-17 10:28:32:795 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@188>Initing new TiVo with <NSNetService 0x60000257ebc0> local. _http._tcp. Bedroom 80
2019-12-17 10:28:32:795 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@192>Created new TiVo Bedroom disabled with <NSNetService 0x60000257ebc0> local. _http._tcp. Bedroom 80
2019-12-17 10:28:32:795 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@198>Created new TiVo Bedroom disabled with <NSNetService 0x60000257ebc0> local. _http._tcp. Bedroom 80
2019-12-17 10:28:32:795 -[MTTiVoManager netServiceDidResolveAddress:]@2122>Disabled TiVo: Bedroom disabled at 10.0.1.24
2019-12-17 10:28:32:821 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@188>Initing new TiVo with <NSNetService 0x60000242c260> local. _http._tcp. Den 80
2019-12-17 10:28:32:821 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@192>Created new TiVo Den disabled with <NSNetService 0x60000242c260> local. _http._tcp. Den 80
2019-12-17 10:28:32:821 -[MTTiVo initWithTivo:withOperationQueue:manual:withID:withSerialNumber:]@198>Created new TiVo Den disabled with <NSNetService 0x60000242c260> local. _http._tcp. Den 80
2019-12-17 10:28:32:822 -[MTTiVoManager netServiceDidResolveAddress:]@2122>Disabled TiVo: Den disabled at 10.0.1.12
2019-12-17 10:28:53:454 -[MTAppDelegate cleanup]@1451>cTiVo exiting

**Comment by esharakan** [comment] 2019-12-17 15:38
OK I cleared out the Prefs file again, and this time launched with the control & option keys pressed.  As expected, it still failed.  I'm attaching the more verbose log.
[com.cTiVo.cTiVo 2019-12-17--04-25-50-533.log](https://github.com/mackworth/cTiVo/files/3974083/com.cTiVo.cTiVo.2019-12-17--04-25-50-533.log)

**Comment by mackworth** [comment] 2019-12-17 15:59
Did it ever ask for the MAK when you ran it from a clean prefs point?  BTW, never got the prefs file, can you double check spelling?  (There's a K in there)

**Comment by esharakan** [comment] 2019-12-17 16:06
No, it never asked for the MAK.

I did have a typo in your address (not the missing 'k' though), you should be getting it now.

**Comment by mackworth** [comment] 2019-12-17 17:03
hmm. Still not on the email.

**Comment by esharakan** [comment] 2019-12-17 17:48
That's odd.  Let me try sending it from a different account

**Comment by esharakan** [comment] 2019-12-29 03:28
So I tried it again today, and one of my TiVos properly showed up under Local Network TiVos.  I deleted the one I added manually and restarted cTiVo, and now they both appear under Local Network TiVos!  They showed up disabled, but I simply enabled them and it worked fine.

The only thing different I can think of is that I rebooted my laptop a few days ago, because it had problems sharing files from my Mac Mini on the local network.  I could do screen sharing but not file sharing.  So maybe this was some issue with Bonjour service discovery that got cleared when I rebooted.

**Comment by mackworth** [comment] 2019-12-30 17:05
Well, glad to hear it.  Let me know if it resurfaces.

**Closed by mackworth** 2019-12-30 17:05 UTC

**Comment by gfitzp** [comment] 2020-01-28 05:27
I'm having the same issue, 3.4.1 on macOS Mojave 10.14.6, even after restarting Mac and TiVo and router each a few times just in case. I've attached my logs just in case it might be helpful for finding the root cause, but it appears that I can also add the TiVo manually for the time being.
[com.cTiVo.cTiVo 2020-01-28--05-04-31-375.log](https://github.com/mackworth/cTiVo/files/4120769/com.cTiVo.cTiVo.2020-01-28--05-04-31-375.log)
