### ISSUE TITLE
Download Keeps Failing

### ISSUE THREAD

**Issue by rwheeler56** [mackworth/cTiVo#405] opened 2020-01-29 22:49 UTC
I have attached the log for a recent download from my Tivo Bolt.  It keeps failing.  I checked the recording and all is well with it.  I have rebooted both my MAC and Bolt to no avail.  Can you assist with what might be causing this issue?  I've had this problem with two other TV shows downloading from last night; however, other shows downloaded just fine.

[com.cTiVo.cTiVo 2020-01-29--03-07-02-442.log](https://github.com/mackworth/cTiVo/files/4131200/com.cTiVo.cTiVo.2020-01-29--03-07-02-442.log)

**Comment by rwheeler56** [comment] 2020-01-31 20:29
UPDATE:

It would appear that downloads work "most" of the time; however, those that are failing are "not" from the same network.  It appears to be random.  

Mac any ideas on what might be causing this all of a sudden ?  cTivo usually works flawlessly.

**Comment by rwheeler56** [comment] 2020-02-25 14:35
UPDATE:

Hey Mac.  I haven't heard back from you on the issue.

Just wanted to let you know that this is still happening; however, it is very random, in that, it's not always the same show/channel, etc..  Could it have something to do with the latest version of Catalina ?

**Comment by rwheeler56** [comment] 2020-03-06 21:30
hey mac.

did i post this in the wrong place?  Are you able to see the post ?

I'm not sure if this is just affecting a few users of the product or if it is affecting many.

Can you at least let me know if you are aware of the issue ?

**Comment by mackworth** [comment] 2020-03-06 21:31
My apologies for the delay; I've been very impolite. 

I've looked briefly at your case, but haven't been able to see anything quick. I've been absorbed on another project, so I'll get back to this soon.

**Comment by rwheeler56** [comment] 2020-04-21 13:55
Hey my friend.

I know you have probably been very busy.  Just wanted you to be aware that this issue is increasing with the number of failed downloads.  Something is obviously going on and I have a feeling that it is related to the MAC OS Catalina.  As far as I know, Tivo hasn't changed anything other than those annoying TIVO+ Commercials; however, I got rid of those by calling and requesting they be removed.  However, each time Tivo pushes an update so do the Tivo+ Commericials return but I still call them to remove them.  

Any help you can provide would be most graciously appreciated.

Thanks Mac !

**Comment by mackworth** [comment] 2020-05-09 17:18
You really have gotten abysmal service here. I apologize.  Part of the reason is that the more I look at this, the more this seems to be a general TiVo problem; TiVoCommunity shows PC-downloading software having the similar issue of corrupted files. 

The download process is very sensitive to these issues, so sometimes it translates to an inability to download beyond a certain point, other times the decryption process fails. Not much we can do at the receiving end of the chain. I note in your logs that both commercialing and encoding failed (separate software from two different projects), further suggesting that there's some kind of corrupting in the file itself.

Only other thing I can suggest is to ensure that your cable signal is good (especially if there are certain channels that fail regularly). There's a test page in the TiVo menus for signal strength.  Let me know what you find.

**Comment by rwheeler56** [comment] 2020-05-09 18:13
Digital signal strength on all channels that have failed, and it is sporadic and doesn’t occur all time is at 97%. 

Thanks
Ray

**Comment by rwheeler56** [comment] 2020-05-11 10:35
Meaning, show The Rookies, failed last night. However, last week it completed. Signal strength on that channel is 97%. 

It would not surprise me if this really is a Tivo issue, in that, users of TiVo’s download product are having the same issues....

Thanks
Ray

**Comment by rqchin** [comment] 2020-05-11 16:53
Attaching a log file for three files that keep failing when trying to download/convert. One has been failing since 11/27/19; the other two are Disney shows and perhaps Disney has done something to prevent downloading
[com.cTiVo.cTiVo 2020-05-11--08-30-00-800.log.zip](https://github.com/mackworth/cTiVo/files/4610967/com.cTiVo.cTiVo.2020-05-11--08-30-00-800.log.zip)
.

**Comment by mackworth** [comment] 2020-05-11 17:39
So the Supergirl and Disney Volume II look like traditional file corruption issue.  Nothing I can do about those. But I note that they failed within the first few seconds; you could try forcing them to download as Transport Stream instead of Program Stream, and see if that works. If it does let me know; I could add a test for that scenario.

On the other hand, Disney Volume 1 is complaining that the name is too long:  
>  /Volumes/easystore 8TB/zctivotemp/decryptThe Disney Family Singalong - 2020-04-16 - Christina Aguilera,Erin Andrews,Bobby Bones,Michael Bublé,Kristin Chenoweth,Auli'i Cravalho,Luke Evans,Jordan Fisher,Josh Gad,Derek Hough,Julianne Hough,Carrie Ann Inaba,Kenny Ortega,Donny Osmond,Thomas.txt

So you can certainly see its point. :)

cTiVo is supposed to truncate names that are too long (no more than 255 chars per component), which is why it ends with "Thomas", but as that still left 256 characters, it appears that it isn't doing it quite aggressively enough.   (Old joke: there are two hard problems in computer science: cache invalidation, naming things, and off-by-one errors)

So, as a workaround, if you temporarily change the filename template to remove the guest list, you should be able to download it.

**Comment by rqchin** [comment] 2020-05-11 18:16
Those 8-bit limits strike again! I think I've figured out how to update the file name. How do I tell cTivo to try those two shows using Transport Stream?

**Comment by mackworth** [comment] 2020-05-11 18:54
Turn queue off (Cmd-U)
Right-click in header of Download Queue, and turn on "Use TS" column.
Drag your two shows in Download queue (or if still there, right-click and Reschedule)
Check "Use TS" boxes

**Comment by mackworth** [comment] 2020-05-11 19:01
Not a high probability of working, but worth a try.

**Comment by rqchin** [comment] 2020-05-11 21:52
Interesting. One that failed previously succeeded (Disney Singalong) using TS. Supergirl failed both ways. Disney Singalong II, which previously failed due to filename length, now fails using either method.

BTW, I really like that old joke! I've never heard it before but I'm going to use it!
[com.cTiVo.cTiVo 2020-05-11--08-30-00-800.log.zip](https://github.com/mackworth/cTiVo/files/4612293/com.cTiVo.cTiVo.2020-05-11--08-30-00-800.log.zip)

**Comment by mackworth** [comment] 2020-05-11 22:48
actually looking at the log, it's what I pretty much expected:  The Disney Family Singalong (not II) failed before due to the long filename and downloaded properly this time, but Supergirl and Disney both tried Transport Stream, and failed, auto-switched to Program and failed again. 

If you have a place you can upload a large file (not here), then can you download Supergirl and post it somewhere.  Given that it fails so quickly into the file, I'd like to see if I can diagnose what's causing that.  Just use your browser to download with [this URL](http://dvr-162b.local.:80/download/Supergirl.TiVo?Container=%2FNowPlaying&id=311097). You could actually interrupt it after, say, ten seconds, as I won't need to get beyond that.

To diagnose, I'll need your MAK, so if that's ok, you can email me that at mackworth at aol dot com.

**Comment by mackworth** [comment] 2020-05-11 22:53
BTW, a great thing to try would be the tivolibre program. 
You have to have Java runtime installed on your machine to run it.  If you want to do that, just [go here](https://www.java.com/en/download/) to install it.  Then in cTiVo Advanced Preferences select Decode With: TivoLibre. Then try running the downloads again.

**Comment by rqchin** [comment] 2020-05-11 22:55
OK, I do have a place to handle large files, so I'll get you that and the MAK. After that, I'll try tivolibre - hadn't heard of it before.

**Comment by rqchin** [comment] 2020-05-11 23:00
@mackworth Would the username and password for that local URL still be my online TiVo username and password?

**Comment by mackworth** [comment] 2020-05-11 23:02
Sorry I forgot to mention that.  It’s just tivo for the username and yourMAK for the password.

**Comment by mackworth** [comment] 2020-05-27 17:36
Any luck?

**Comment by rwheeler56** [comment] 2020-05-27 19:20
Ah, any luck with what. I think so other person was using my post to report an issue and you were responding with him. 

I am still having the issue, which I believe I already stated started after Apple release a patch for Catalina a while back. At this point, I cannot tell you when that patch happened because this issue has been happening for so long. 

You may have access to all the catalina patches apple released to determine what patch may have affected your software to stop working 100%. 

Thanks
Ray

**Comment by rqchin** [comment] 2020-05-27 19:33
I've got the file downloaded. I'll send it. I'm trying TivoLibre but everything fails with that choice. Where should I put the TivoDecoder.jar file? I have it in Applications at the moment.

**Comment by mackworth** [comment] 2020-05-27 19:34
Correct, that was to @rqchin.  On the other hand, did you ever try Handbrake formats instead? In further research, I found that this is a known ffmpeg issue. Handbrake may run into the same thing, but it would be worth a try.

**Comment by mackworth** [comment] 2020-05-27 19:40
@rqchin: that's built in, no need to add it.  Can you post your log, to see what the problem is?

**Comment by rqchin** [comment] 2020-05-27 19:47
Ah, you added the TivoLibre into your code - genius! Here is the log.
[com.cTiVo.cTiVo 2020-05-27--18-00-00-601.log.zip](https://github.com/mackworth/cTiVo/files/4691376/com.cTiVo.cTiVo.2020-05-27--18-00-00-601.log.zip)

**Comment by mackworth** [comment] 2020-05-27 19:51
You're getting the msg: java.lang.UnsupportedClassVersionError: net/straylightlabs/tivolibre/DecoderApp : Unsupported major.minor version 52.0

Not being a Java expert, the internets tell me that this means "the class was compiled at a higher version of Java than the version with which we tried to run it." And that 52.0 is version 8 of Java.

Sounds like you need to update your Java runtime?

**Comment by rqchin** [comment] 2020-05-27 20:04
Hmm, I just downloaded it a few minutes ago. It says it is the recommended version for my system.  (MacOS 10.14.6)
It is Java 8, version 251
![Java 8 Version 251](https://user-images.githubusercontent.com/33967440/83066869-b8a7c380-a033-11ea-99df-56597b36a632.jpg)

**Comment by rqchin** [comment] 2020-05-27 20:13
Supergirl file link sent with MAK so you can inspect it and see why it fails so quickly.

**Comment by rqchin** [comment] 2020-07-19 23:52
Java just updated to Java 8 Update 261 today, so I'm going to try it again.

**Comment by mackworth** [comment] 2020-10-15 21:58
So @rwheeler56  is on another thread now.  Did upgrading to 261 fix the java error msg for @rqchin?

**Comment by rqchin** [comment] 2020-10-15 23:28
It failed like before but I think that was expected. How do I tell if it asking for the right version of Java? Log attached.
[com.cTiVo.cTiVo 2020-10-15--00-12-00-224.log.zip](https://github.com/mackworth/cTiVo/files/5388362/com.cTiVo.cTiVo.2020-10-15--00-12-00-224.log.zip)

**Comment by mackworth** [comment] 2020-10-26 20:21
Sorry, missed the response.  The log is indicating you're trying tivodecode-ng, not TiVoLibre. It's reporting an Invalid MAK, which you should confirm isn't the case. (That message will also happen if there's decryption error).

**Comment by mackworth** [comment] 2020-11-13 23:21
So closing this for now. If you'd like to work it out, please open a new issue, as this one has gotten off topic...

**Closed by mackworth** 2020-11-13 23:21 UTC
