### ISSUE TITLE
Unable to get cTiVo to cut commercials

### ISSUE THREAD

**Issue by mjasithrive** [mackworth/cTiVo#381] opened 2019-09-02 18:02 UTC
hello. im having issues getting the com skip mode to work, (Mac Version 3.3.2 beta 3 (1069)). not sure if this is the correct area to post this. I think I have all the settings correct according to the documentation, but I still end up with a full uncut file. is there a step I'm missing? the com data is being downloaded. do I need to download a Comskip script or app? thanks in advance for any help. 
![MJ_MBP_ScreenShot 2019-09-02 at 12 54 36 PM](https://user-images.githubusercontent.com/54726927/64129436-9709fc00-cd81-11e9-8312-9d55fe589cf0.jpg)
![MJ_MBP_ScreenShot 2019-09-02 at 12 55 03 PM](https://user-images.githubusercontent.com/54726927/64129437-9709fc00-cd81-11e9-8b0b-e8972b000b0c.jpg)
![MJ_MBP_ScreenShot 2019-09-02 at 12 55 19 PM](https://user-images.githubusercontent.com/54726927/64129439-9709fc00-cd81-11e9-94bd-5325251db74a.jpg)
![MJ_MBP_ScreenShot 2019-09-02 at 12 55 33 PM](https://user-images.githubusercontent.com/54726927/64129440-9709fc00-cd81-11e9-98d4-945ad5e87fa1.jpg)
![MJ_MBP_ScreenShot 2019-09-02 at 12 55 47 PM](https://user-images.githubusercontent.com/54726927/64129441-9709fc00-cd81-11e9-834e-0a95e3a0db3e.jpg)

**Comment by mackworth** [comment] 2019-09-02 18:22
Yes, this is indeed the place.

Thanks for the images. The problem is your Format, "Decrypt MP4-1". "Decrypt MP4" copies the video stream over without re-encoding at all, and so it cannot do any manipulations such as cutting sections. (The original "Decrypt MP4" has "Can Skip commercials" turned off for that reason. Changing that setting doesn't give ffmpeg the ability to do so, rather it informs cTiVo incorrectly that ffmpeg can do such cutting.

If you change to Default Format or another that has Can Skip marked, you should be fine on being able to Cut. 

If you don't want to re-encode, then cTiVo can Mark commercials instead, which simply adds the jump points as Chapters, making it easy to jump across them.

BTW, I hadn't previously noticed that after TiVo introduced SkipMode and I renamed "Skip Commercials" to "Cut" to avoid confusion, I missed the labeling in Edit Formats, so I will change that in the next version.

**Comment by mjasithrive** [comment] 2019-09-02 22:52
Thank you so much for the quick reply! Got it to work, YAY! For some reason I never tried the other decoding options (other than download decrypted Tivo) as I was opening the decrypted Tivo TS in Avidemux to cut commercials then to Handbrake for compression. But recently I'm having trouble w/ Avidemux and h.264/.mp4 files. some of my Comcast channels are now h.264. What's a good editing program (to cut commercials) I could use to keep all the audio (surround sound) and HQ video intact without re-encoding? Or is that even possible with h.264? thanks again!

**Comment by mackworth** [comment] 2019-09-02 23:37
So the Default format will use ffmpeg, can handle TS/MP2 or PS/H264, can Cut the commercials, and will keep multichannel audio (adding a stereo) and full video quality (up to 720p, use the 1080p Format if you want higher). It does re-encode, but only once to get to your final output, with no manual steps required. 

Let me know if that’s not what you’re looking for!

**Comment by mackworth** [comment] 2019-09-05 16:54
I take it the issue is resolved, so I'll close this for now. Let me know if you need any furthre assistance.

**Closed by mackworth** 2019-09-05 16:54 UTC

**Comment by mjasithrive** [comment] 2019-09-05 18:10
Thank you. I do have it working now. Do you have any recommendations for Mac video editing software for when I have to manually trim out commercials? I currently use Avidemux and it seems to work well for ts streams, but not for h264 streams. 


- - - -
Mike Jasinski

**Comment by mackworth** [comment] 2019-09-05 18:11
Sorry, haven’t really done much of that.

**Comment by mjasithrive** [comment] 2019-09-05 19:12
Thanks!
