### ISSUE TITLE
Video Files have tears and audio errors

### ISSUE THREAD

**Issue by cbibbs** [mackworth/cTiVo#511] opened 2023-02-16 13:52 UTC
I'm using an M1 Macbook to download and encode shows off my Tivo. Right now I can watch all the shows directly on the Tivo or my Tivo Mini just fine. However, the video files that come out of cTivo are full of encoding errors. I've tried all of the default formats including "Decrypted Tivo Show". I suspect something is going wrong in the download process, but I have no idea how to verify that.

Any thoughts

**Comment by mackworth** [comment] 2023-02-16 14:19
So, this is a well-known TiVo problem been going on for years. ([More cTiVo-specific discussion here](https://github.com/mackworth/cTiVo/issues/460).) 

TiVo's encrypting software introduces (or magnifies) glitches in the downloading stream.  It seems to be specific to the Edge (which I don't own), and the theory is that it's due to the higher networking speed reducing the time for the CPU to properly encode, and TiVo doesn't care. There's a [great summary of the situation here](https://www.tivocommunity.com/threads/edge-to-pc-downloads.587636/). 

You could try doing the same network-slowing test that they describe by running Apple's Network Link Conditioner, which gives you direct control over the network speed/quality.  [Good description of it here](https://nshipster.com/network-link-conditioner/). 

If that helps, I've offered a couple of times to produce a version of cTiVo that does some of this network slowdown itself, but I'd need a volunteer with an Edge who has a reproducible case to run a lot of test software. (I'm also traveling for a bit so wouldn't be able to get to it for several weeks)

**Comment by cbibbs** [comment] 2023-02-16 14:45
@mackworth thanks for the pointer, my searches didn't turn that thread up. I'll run some experiments with the Link Conditioner set to 3G and let you know how it goes. I have a few test machines that I can use so it doesn't disrupt my work life.

**Comment by mackworth** [comment] 2023-03-07 22:59
Any luck?

**Comment by mackworth** [comment] 2023-03-09 23:13
sigh, sorry to hear that. Well I'm going to close this one as I believe it's the same as #460

**Closed by mackworth** 2023-03-09 23:13 UTC
