### ISSUE TITLE
Crashing new Tivo Edge. Fixed?

### ISSUE THREAD

**Issue by chwhite** [mackworth/cTiVo#397] opened 2019-11-28 14:48 UTC
Hello,

I have a new TIvo Edge. Whenever cTivo starts to download a show the Edge crashes. Is this a known issue? This is with the latest 3.4.1 release. Tivo software version 21.9.2.1.v8-USM-12-D6F. I've been using cTivo for years with a Romio Pro before this.

**Comment by mackworth** [comment] 2019-11-28 15:51
I doubt it's the Edge, there's probably another reason. Which "version" of 3.4.1?  in About cTiVo, look for the number like (1108).  I just finished the beta cycle, and released the final version 1108 yesterday, which fixed a couple of anonymous crashes that Crashlytics reported.  FYI, the only other one I see is one where dragging files occasionally crashes, but I haven't been able to reproduce that one.

Assuming it is 3.4.1 v1108, or if switching to 1108 doesn't fix your problem:
- Which version of MacOS are you running? 
- What kind of Mac (and what specific model/year also from About this Mac, so I can try to match your crashes with what Crashlytics reports)
- Put logging on Verbose mode, and run it again until it crashes; 
- Note the time (and timezone), again so I can match it up)
- then Help>Show Files in Finder, 
 - then in Finder, right-click and Compress the files, 
 - then post the result here (Not via email, come to this issue on Github)
- Be sure to run cTiVo again after posting, so that Crashlytics has a chance to post your crash results

thanks

**Comment by chwhite** [comment] 2019-11-28 16:28
I was on 1101, switched to 1108, deleted all the preferences and application support files and 1108 still crashes. 

- Catalina 10.15.1
- Mac mini (2018 3.2GhZ i7 32GB) Macmini8,1
- 2019-11-28 08:21:14:362 - PST is when I initiated the download and it crashed, logs are attached. 

[com.cTiVo.cTiVo 2019-11-28--13-40-40-320.log](https://github.com/mackworth/cTiVo/files/3902500/com.cTiVo.cTiVo.2019-11-28--13-40-40-320.log)

**Comment by mackworth** [comment] 2019-11-28 17:09
Oops, after not seeing a cTiVo crash in the logs I just re-read your first message. The TiVo itself is crashing? Going through the full reboot cycle? That's extremely strange.  I think you've got a hardware problem. 

Try this URL (it'll ask for your username: tivo and password: your MAK)
[Now Playing](https://dvr-d9f1.local./nowplaying/index.html)

Then click on "download MPEG-PS" on one of the shows. It should crash your TiVo. (If not, cancel the download after a little bit.) Assuming it does, you have a clean reproducible case for TiVo Tech Support that doesn't involve cTiVo or anything on your Mac other than the browser.

**Comment by Tivo2** [comment] 2019-12-07 17:03
I have the same issue tivo edge reboots when ctivo accesses it.

**Comment by mackworth** [comment] 2019-12-07 17:40
Very disturbing to have a second case, but if it's the Tivo's internal system crashing, there's really nothing I can do about it. Is this also a brand new TiVo; maybe a bad hardware batch? 

Just to confirm, can you follow the same process?  

If you: 
- set your Preferences>Debug Log to Major, 
- try to download a show (presumably the TiVo reboots)
- Help>Show Logs in Finder, and 
- double-click on the last one, 
- In Console, put `Starting URL http://` into the search box
- you'll see a line like:
`2019-11-28 05:40:47:824 -[MTDownload launchDownload]@1895>Starting URL http://dvr-d9f1.local.:80/`
- Note the four letters after `http://dvr-` (e.g. d9f1 above)
- Now use your browser to open `https://dvr-XXXX.local./nowplaying/index.html`, (
replacing the XXXXs with your TiVo's letters).  BTW, the period after `local` is essential.
- username: `tivo` and password: `your MAK`
- Now click on "download MPEG-PS" on one of the shows. 

It should crash your TiVo. (If not, cancel the download after a little bit.) Assuming it does, you now have a clean reproducible case for TiVo Tech Support that doesn't involve cTiVo or anything on your Mac other than the browser.  Please let me know either way. @chwhite any update on your case?

**Comment by Tivo2** [comment] 2019-12-07 21:51
Yes that process rebooted the tivo edge  as well

**Comment by mackworth** [comment] 2019-12-07 21:55
And is it a new Edge? Or did it work before with cTiVo?

**Comment by Tivo2** [comment] 2019-12-07 22:49
It is new this is the first attempt with ctivo

**Comment by mackworth** [comment] 2019-12-07 23:35
Interesting!  Maybe a bad batch of TiVos.  If @chwhite is still out there, maybe you two should coordinate.

**Comment by mackworth** [comment] 2019-12-14 17:34
@chwhite are you out there?

**Comment by chwhite** [comment] 2019-12-14 17:38
I am, and I am still having the issue. Forgive the delay, I have been traveling for work the last couple weeks. I intend to try and RMA the Edge later next week when I am home and have some time. Will report back as to whether or not the replacement behaves the same.

**Comment by mackworth** [comment] 2019-12-14 17:40
Thanks!  and @Tivo2, have you been able to interact with TiVo support along the same lines?

**Comment by mackworth** [comment] 2019-12-30 17:05
Any updates from TiVo for either @chwhite  or @Tivo2 ?

**Comment by chwhite** [comment] 2020-01-01 19:26
I steeled myself up to call just now. After a couple attempts and calls and a couple different support people I finally explained what I was doing. He walked away came back and said "those features aren't supported on the Edge". I didn't believe him and pressed then he started saying this was Apples problem. Again explained it wasn't Apple and that you'd verified other people were using the edge cable box successfully. I sat on hold for 20 minutes while they tried to find "staff" who can support the Edge and gave up. 

You do have other people using the Edge (cable card version) successfully right?

**Comment by mackworth** [comment] 2020-01-01 20:02
Apparently not; I did some more research, and found [this article from TiVo_Ted](https://www.tivocommunity.com/community/index.php?threads/edge-issues-were-tracking.573641/)

 It indicates that the TiVo-To-Go capability (that cTiVo uses) is a known problem, that it crashes the Edge, is not currently supported, and may never be supported. If I were you, I would add a comment onto that thread, so that they know there are people concerned about this loss.

I'll add a note to cTiVo's intro page reflecting this.

**Comment by Tivo2** [comment] 2020-01-02 14:09
Yeah this is disappointing....I'll probably just upgrade my bolt hard drive then....and wait......


    On Wednesday, January 1, 2020, 02:02:45 PM CST, Hugh Mackworth <notifications@github.com> wrote:  
 
 
Apparently not; I did some more research, and found this article from TiVo_Ted

It indicates that the TiVo-To-Go capability (that cTiVo uses) is a known problem, that it crashes the Edge, is not currently supported, and may never be supported. If I were you, I would add a comment onto that thread, so that they know there are people concerned about this loss.

I'll add a note to cTiVo's intro page reflecting this.

**Comment by mackworth** [comment] 2020-05-09 17:22
Yay!  This one seems to be fixed by TiVo finally.  Apparently you need software release 21.9.7.v3-USM-12-D6F. Let me know if it works.

**Closed** 2020-10-15 22:53 UTC
