### ISSUE TITLE
cTiVo requires user's  permission to access Handbrake's custom presets

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#528] opened 2023-12-20 00:10 UTC
I updated to Handbrake 1.7.1 and now the popup comes in to let cTiVo have access to the app. Is this just me or are others having this problem will using the HandbrakeCLI?

As a result all cTivo Downloads fail to encode and are finally erroring out based on the max retries.

Apple silicon
MacOS 14.2.1
Handbrake 1.7.1
cTiVo 3.6.2

**Comment by tdlivings** [comment] 2023-12-27 16:27
I found a work around. I have to open settings to prompt the cross app permissions before I download and encode shows

**Comment by mackworth** [comment] 2023-12-30 17:11
Hi, sorry; distracted by end of year stuff.

Couldn't reproduce the download failure. I have the same versions, and I do get the popup when I run cTiVo's preferences, but I don't get it when cTiVo just runs a Handbrake-encoded download (restarting in between as you'll only get that warning once per run).  I tried with the default .sh version (which runs a script that runs Handbrake) as well as with a direct HandbrakeCLI call using both the built-in and the 1.7.1 CLI version (downloaded separately from the GUI).  

So this changed for you when you updated Handbrake GUI to 1.7.1? And if it comes on the download, you can't just hit Allow?

There seems to be no way to avoid that popup message on the Prefs launch. If we can't fix the "won't download without the prompt", then I could move the prompt to initial app launch, so you wouldn't have to remember to open Prefs before downloads.

**Comment by tdlivings** [comment] 2023-12-30 19:11
Yeah, I just open settings before the download to get the prompt. If I don't the encode will not give me the prompt and will fail until the max tries are reached. Not clean but it works.

**Comment by mackworth** [comment] 2023-12-30 20:34
Which Format are you using?

**Comment by tdlivings** [comment] 2023-12-30 20:37
[H.264 TiVo PP-VTB 78 NF 2P.json](https://github.com/mackworth/cTiVo/files/13799154/H.264.TiVo.PP-VTB.78.NF.2P.json)

**Comment by mackworth** [comment] 2023-12-31 00:27
Ah, that's it. Because you're using a custom Handbrake preset, the HBCLI has to read it from the sandboxed Handbrake directory, which Sonoma doesn't allow without permission. (Same with Preferences, which loads the names of any custom Presets.) 

Oddly, it's the HandbrakeCLI that's actually doing the reading, which one would think would have permission to read its own directory., but it's being called as a subprocess from cTiVo, so it must inherit cTiVo's lack of permission to read that directory.

I'll see if I can make it better. Should upgrade to 1.7.1 anyways.

**Comment by tdlivings** [comment] 2023-12-31 00:29
No rush, I got it working with a work around. It is strange that it didn't happen until I update handbrake. But then maybe it was my imagination and it was actually a Sonoma update... who knows

**Comment by mackworth** [comment] 2023-12-31 00:33
I changed the title to warn others hitting same problem. Can you just confirm that if you exit and restart cTiVo and then download a show using handbrake with a built-in preset, say, the Default HB HW Format that it runs without holding you up for permission?

**Comment by tdlivings** [comment] 2023-12-31 00:43
Stock HB Default works. I will try and change my custom to use HandbarakCLI.sh and see what happens

**Comment by tdlivings** [comment] 2023-12-31 00:46
Well at least I got the cross app prompt that time...Maybe it could be because my profile is stored in a different directory now.

**Comment by mackworth** [comment] 2023-12-31 00:49
Nope, it's not the "calling CLI directly" vs "calling from shell script"  that matters, only if the resulting CLI process tries to read the HB presets list (created by the GUI in Handbrake directory). So if you want to use your custom preset, then you'll hit that prompt.

**Comment by tdlivings** [comment] 2023-12-31 00:51
Yes, its ok

**Comment by tdlivings** [comment] 2023-12-31 00:53
Final Cut really took off. I am getting an H.265 8-bit for a 45 minute show at 960x 540 in one minute...

**Comment by mackworth** [comment] 2023-12-31 01:08
It's some impressive hardware. 

In reading about how to prevent this popup, Apple says "this message may appear if you change signing keys between versions". 

When I build with 1.7.2 CLI, and run, I don't get the prompt, so they may have changed keys with 1.7.x

Can you see if that's the case on your machine?  Try [downloading the CLI here](https://handbrake.fr/rotation.php?file=HandBrakeCLI-1.7.2.dmg) , open the DMG and drag the CLI file onto the "Encoder to use" field in a Duplicate of your custom Format, and Save. Then exit, restart and try using that new Format. Should avoid the prompt.

**Comment by tdlivings** [comment] 2023-12-31 01:18
I already replaced the CLI in cTiVo. That was my first troubleshooting step.

**Comment by tdlivings** [comment] 2024-01-24 02:57
After the latest update to 14.3 the prompt stopped popping up.

**Comment by mackworth** [comment] 2024-05-06 17:01
Just about to release a new version (with updated certificate and handbrake). Just checking that you're still not getting the prompt anymore?

**Comment by mrfusiontm** [comment] 2024-05-06 20:44
Haven't seen it in quite some time.  I've also just recently gotten rid of
cable, so I just turned cTivo off.
I did want to thank you so much for this wonderful tool and the prompt
response you always provided.
I'm not sure how long I've used it, but it's got to be about a decade
maybe?  Your support for your fine software is so much better than I've
seen for expensive software.
Thank you so much.  I truly appreciate it.

Tom

**Comment by tdlivings** [comment] 2024-05-06 22:44
I am not sure who the other response is from, but no, the prompt resolved itself and has not shown its ugly self for a while now. Thanks for asking

Thomas Prime LOL

**Comment by mackworth** [comment] 2024-05-06 23:03
@mrfusiontm  you're quite welcome. I admit to barely using TiVo myself at this point, and the numbers are steadily decaying on cTiVo's usage.

@tdlivings Thanks. I had written some code to work around it back in December, but I'll hold that back for now to avoid unnecessary (and untestable) changes.

**Closed by mackworth** 2024-05-06 23:03 UTC
