### ISSUE TITLE
Subscriptions failing (redux)

### ISSUE THREAD

**Issue by sarpent** [mackworth/cTiVo#385] opened 2019-09-17 18:45 UTC
This isn't actually a new issue, but my last report was closed. I had spoken too soon. It still doesn’t seem to be downloading subscribed shows. I looked inside the (verbose) subscription logs after reapplying, but nothing jumps out to me as wrong. Certainly there are no error messages. The shows that should be downloading most recentely here are "Lodge 49: Circles” and "Country Music: Hard Times".  

Reapplying a subscriptions does work, but it doesn’t catch the next episode when it shows up. Thoughts?

Thanks!

[com.cTiVo.cTiVo 2019-09-16--23-31-09-753.log](https://github.com/mackworth/cTiVo/files/3622956/com.cTiVo.cTiVo.2019-09-16--23-31-09-753.log)

**Comment by mackworth** [comment] 2019-10-26 21:56
Sorry for delay in responding. (Partly due to travel and partly due to wanting to get the Catalina compatible version out.) 
 This is a complex problem, and the logs aren't quite giving me enough info. It seems to be something to do with quitting cTiVo while a show is being recorded and then starting up again at least 12 hours later....or maybe something else entirely. So...assuming it's still happening to you, I'd like you to run this test version for a while (with Subscriptions at Verbose) until it happens again.
https://www.dropbox.com/s/atgbgbls55dyygk/cTiVoSubscribe.app.zip?dl=0

**Comment by sarpent** [comment] 2019-10-27 19:56
Thanks Hugh. I’ve installed it and will let you know.

**Comment by mackworth** [comment] 2019-11-12 01:23
No recurrence?

**Comment by sarpent** [comment] 2019-11-12 15:54
It’s still happening, and it’s inconsistent. In my latest launch of the app this morning, it should have downloaded “Treadstone: The Kentucky Contract,” which it didn’t. It did download “The Walking Dead: Bonds,” but it skipped the previous episode, “The Walking Dead: No One’s Gone” and three other previous Walking Dead episodes. I've attached the log file. Thanks!
[com.cTiVo.cTiVo 2019-11-12--13-52-12-415.log](https://github.com/mackworth/cTiVo/files/3837026/com.cTiVo.cTiVo.2019-11-12--13-52-12-415.log)

**Comment by sarpent** [comment] 2019-11-12 16:06
Also, I should note that I'm pretty sure that I've never quit the app while a file was downloading. Thanks.

**Comment by mackworth** [comment] 2019-11-12 19:17
I found it -- at least I think.  

Sequence of events:
A) cTiVo starts
B) Ask TiVo for current list of Now playing shows 
C) TiVo starts sending first chunk of that list
D) cTiVo checks those shows for subscriptions (versus last time we got a list, long ago)
E) Unusually, your TiVo sends a change notice about the list
F)  cTiVo then properly asks for the whole list of shows again (so it has a clean list) 
G) Tivo sends over the whole list in chunks

The problem is that when F happens, cTiVo incorrectly remembers the prior, interrupted-list download B as "the last time we checked our subscriptions", so any shows that were delivered during C will get checked for subscription, but any other ones delivered only during F will not get checked.

Easy to fix, now that I see it, but the other question is why is your TiVo doing that update?  Can you set the general Debug level to Major and TiVo debug level  to Detail in Adv Preferences, then exit and reenter, then submit the log again?

Here's a version with the fix in it...

https://www.dropbox.com/s/ozhkw2nqjrrbefa/cTiVoSubscribe.app.zip?dl=0

**Comment by sarpent** [comment] 2019-11-12 19:24
I've attached the logs following your instructions. I assumed that you wanted me to do this with the new version that you had attached. Thanks!
[com.cTiVo.cTiVo 2019-11-12--13-52-12-415.log](https://github.com/mackworth/cTiVo/files/3837840/com.cTiVo.cTiVo.2019-11-12--13-52-12-415.log)

**Comment by sarpent** [comment] 2019-11-12 19:26
Also note that I don't believe that there were any outstanding subscription downloads in that log. I had manually downloaded the files that I believe were missing. I hope that doesn't mess up your diagnostics.

**Comment by mackworth** [comment] 2019-11-12 21:47
Thank you for that log; I've found a "race" condition which i have fixed in a [new 3.4.1 beta2](https://github.com/mackworth/cTiVo/releases/tag/3.4.1beta). Please switch over to this one.

And thank you for reporting the initial problem and sticking with me through the fix! Makes it better for everyone. If you can leave subscriptions at Verbose for a while, that would be good. I'm 99% sure I've fixed your problem, but if you see another missing show, I'd love to get the logs then.

I'll close this for now, but do let me know if there's still any problem.

**Closed by mackworth** 2019-11-12 21:47 UTC

**Comment by sarpent** [comment] 2019-11-12 21:54
Thanks Hugh! I will be running the beta.
