### ISSUE TITLE
Subscriptions sometimes don't record

### ISSUE THREAD

**Issue by rqchin** [mackworth/cTiVo#373] opened 2019-04-18 18:45 UTC
I've noticed that on some of my subscribed shows, cTivo won't grab a show that has a subscription and I have to click the show and add it to the queue manually. In this particular example, it is the show Single Parents.

I'm running Mojave 10.14.3 and cTivo 3.3.1b2.

![cTivo Subscribe](https://user-images.githubusercontent.com/33967440/56383675-69645200-61e8-11e9-8725-2302c3d21129.jpg)

**Comment by rqchin** [comment] 2019-04-19 02:33
I think I figured this out. I think this episode was a rerun/duplicate and that's why it didn't automatically download. Does cTivo scan the folders of existing shows before downloading? I've always wondered how I could tell if a show had been previously downloaded since it loses its check mark if you delete the finished job from the queue.

**Comment by mackworth** [comment] 2019-04-19 02:46
That’s correct. Subscriptions track what shows have been recorded due to that subscription and won’t re-enter one (even if you “allow Duplicates” in Adv Prefs), so that is proper behavior.  (FYI, you can also manually Reapply a Subscription, which will go through the NowPlaying list and redo any matching shows, even if previously done.)

In addition, there is a separate mechanism in which downloaded shows are marked with a Spotlight comment `cTiVoDownload` (so you can actually search for that term). That’s what’s used to mark shows as OnDisk.  It shouldn’t lose its check mark (in the Now Playing list) if you delete the Download entry from the queue, only if the file itself is deleted.

Sounds like it’s working as designed, so I’ll close this, but if you do think there’s an issue, just set the Debug level of Subscriptions to Detail and it will give the reason for including or not including a show.

**Closed by mackworth** 2019-04-19 02:46 UTC
