### ISSUE TITLE
handbrake.cli vs handbrakecli.sh

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#523] opened 2023-08-28 16:14 UTC
This is just an observation not really a request for problem solving. Recently I had a melt down and reinstalled all pieces of the TiVo workflow from scratch. In my rebuild I noticed, by copying a HB stock profile and editing it to point to my user output profile, The encoder to use was HandBrakeCLI.sh . This resulted in no sound profiles being embedded in the output file. Once I changed it to handbrake.cli located in your cTiVo build it fixed the problem. This particular issue was on an Apple Silicon unit as listed below. 
Mac Studio - Ventura OS
  Model Identifier:	Mac13,2
  Model Number:	MJMW3LL/A
  Chip:	Apple M1 Ultra
  Total Number of Cores:	20 (16 performance and 4 efficiency)
  Memory:	64 GB

**Comment by mackworth** [comment] 2023-08-30 21:09
Hmm, what were the parameters in the Format you used?  (If you want to Export it and post it here, that'd be great.)

**Comment by tdlivings** [comment] 2023-08-31 15:54
[H.264 TiVo PP-VTB 78 NF 2P.json.zip](https://github.com/mackworth/cTiVo/files/12487981/H.264.TiVo.PP-VTB.78.NF.2P.json.zip)
 Had to zip it because they said file type not supported.

**Comment by mackworth** [comment] 2023-08-31 20:27
I was able to replicate this, and it turns out that's actually "behaving as designed". 

The custom preset you created has Audio>Selection Behavior>Auto Passthru>AAC selected, but none others.  This is shown in the JSON: 
```
AudioCopyMask" : [
        "copy:aac"
      ],
```
Thus if your source file's audio is AC3 (as mine with Xfinity usually is), then it won't pass it through.  Unfortunately, it looks like AAC only is the default for a custom Preset. 

So, if you change that to also pass-though AC3, you should be ok.

**Comment by mackworth** [comment] 2023-08-31 23:47
In reality, one reason for the script is to allow you to select AAC or AC3 or both. Having it not specify the copymask doesn't make sense.

So, for a future release, I've added `--audio-copy-mask acc` or `--audio-copy-mask ac3` to override the copymask of the preset (which you could re-override in cTiVo's Format). Here's a copy if you'd like to try it out. Let me know if it works.

[HandBrakeCLI.sh.zip](https://github.com/mackworth/cTiVo/files/12491604/HandBrakeCLI.sh.zip)

**Comment by mackworth** [comment] 2023-09-23 04:39
This should now be fixed in 3.6.2. Let me know otherwise.

**Closed by mackworth** 2023-09-23 04:39 UTC
