### ISSUE TITLE
cTiVo crashes adding Remote Tivo’s

### ISSUE THREAD

**Issue by sugyfelix** [mackworth/cTiVo#393] opened 2019-11-04 16:29 UTC
New version 3.4.0

First crash: Hit + to add first remote TiVo. Hit enabled before filling anything in. Hit done. CRASH

Second crash: Fill in missing field from above entry. Create new entry. Didn’t fill in media I’d, so enter value in this field. Causes window to scroll sideways so enabled isn’t visible. Hit done. CRASH.

**Comment by mackworth** [comment] 2019-11-04 21:55
Thanks for reporting this. I'm not able to reproduce exactly as described, but I could easily by just erasing the name field and then hitting done. I am also able to reproduce this back in 3.3.1 and even older. I've fixed in 3.4.1, [pre-release available here](https://www.dropbox.com/s/268n3dtio2hfls0/cTiVo.zip?dl=0).  Let me know if this fixes both these crashes for you.

**Comment by sugyfelix** [comment] 2019-11-05 04:40
On a related topic, the new Get Info command. It seems to always be grayed out? I was adding some remote references for my TiVo’s so I could try out the Get Info and the Reboot, when I got the crash issues. Now that I have the remotes TiVo’s listed I don’t see how to use the new commands?

**Comment by mackworth** [comment] 2019-11-05 05:06
It should be active whenever you have a TiVo line selected in Edit>Edit TiVos screen, and when you're in the Remote Control window. Now that you mention it, if you have just one TiVo (or one TiVo selected) in the main window, I guess I could do it there as well. Maybe next time.  Have you been able to crash 3.4.1 with the same behavior?

**Comment by sugyfelix** [comment] 2019-11-06 06:00
I guess I tried selecting a TiVo in the main window on my first attempt. Never thought about using remote control window. Makes sense now, especially since I would probably use reboot from that point.

Tried a few attempts at similar TiVo editing operations and didn’t stumble on anything obvious.

Thanks!

**Comment by mackworth** [comment] 2019-11-12 01:21
This should be fixed in 3.4.1; if anyone runs into a problem, let me know.

**Closed by mackworth** 2019-11-12 01:21 UTC
