### ISSUE TITLE
Won't Download Some Shows

### ISSUE THREAD

**Issue by JimCarr-CM** [mackworth/cTiVo#340] opened 2018-11-01 01:03 UTC
I have several TiVos. On two of them I have episodes of OTA shows that cTiVo is unwilling to download. Other episodes of same show on same TiVo download fine. 

The problem episodes appear just fine in cTiVo's list of shows on the TiVo but selecting them for download does nothing.

This problem occurred in cTiVo 3.1.2 and is not fixed in 3.20 beta 2.

Please advise what additional data I can provide

Thanks

--Jim

**Comment by mackworth** [comment] 2018-11-01 01:35
By “does nothing”, do you mean it tries and fails, or they just sit in the queue?

**Comment by mackworth** [comment] 2018-11-01 11:33
A couple of thoughts:

I’ve recently become aware there is an issue where certain shows are marked as queued, but are not actually in the queue. I’ve seen this happen where a show was in the download queue, was then deleted from the queue, but left marked for some reason. So I have that in my list to find the cause, and fix in the next beta. AFAIK, quitting cTiVo and re-entering should fix any shows mistakenly labeled as queued. Let me know if that’s wrong. (There’s an old joke that there are two hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.  This is an example of the first. )

In this case, it sounds like you’re saying that a show that was subscribed never made it to the queue. (I’m guessing on the “subscribed” part, versus manually added to the queue.) And that even worse, it marked it as queued without ever adding it? So let me know if that’s what you’re seeing. Or if you could give a step by step on what happened, that would be great. 

A second thought is that the queue really isn’t intended for permanent storage, having 1300 entries may slow it down a bit. 
There’s even a menu command to clear the completed ones out. I’ve never tested with that many entries, so that may be triggering an otherwise latent bug.

**Comment by JimCarr-CM** [comment] 2018-11-01 12:10
Manually added to queue. Running MacOS 10.12.6 if that matters. 32GB RAM so shouldn't be an issue there. 2013 MacPro.

Re-start cTiVo indeed removed the check. Won't add to queue.

Cleared history and re-started again.

That got it into queue and is in progress.

I should note that while there were 1300 shows in history, I was able to add other shows to queue and they downloaded fine so maybe not as simple as too big a history.

At this fixes my issue for tonight as I fight the battle of TiVos that are over 97% full.

Thanks

**Comment by roger88dc** [comment] 2018-11-25 19:08
Hope i all this right i am new to cTiVo and Mac. Finally got t6 TiVo to connect to box. All recordings show up. When i put in que they eventually fail to d/l to macbook air. Some say encoding or ready. One did but will not let me access it in doc folder format mp4 31.MB. No other prog showing all details in top area will download. All say ready or encoding but nothing happens. 
Also do i need toast pro or titanium to watch on mac. Also tried tivo desktop on pc and they d/l but i dont see anything in wmp huge file but won’t play. I am happy to use pc or mac. Just need one to work.

**Comment by roger88dc** [comment] 2018-11-25 20:32
Super newbie Hugh. 
I think i  did what you asked for. Appreciate your help. 

In documents i can see MPEG4
An mp4 file i cant open
QuickTime says it cant open 
I dont see it in itunes either

Roger B

**Comment by roger88dc** [comment] 2018-11-25 21:08
[com.cTiVo.cTiVo 2018-11-24--02-30-00-807.log.zip](https://github.com/mackworth/cTiVo/files/2613509/com.cTiVo.cTiVo.2018-11-24--02-30-00-807.log.zip)
[com.cTiVo.cTiVo 2018-11-25--03-57-17-261.log.zip](https://github.com/mackworth/cTiVo/files/2613511/com.cTiVo.cTiVo.2018-11-25--03-57-17-261.log.zip)

**Comment by roger88dc** [comment] 2018-11-25 21:52
I click on that link at it takes me to the tivo logon page. When I put info in I got


HTTP Status 404 - /tivo-mma/dvrpref.do%E2%80%9D

type Status report

message /tivo-mma/dvrpref.do%E2%80%9D

description The requested resource is not available.

VMware vFabric tc Runtime 2.8.2.RELEASE/7.0.35.B.RELEASE



I have logged in that page b4 and enabled video sharing.
Don’t know why it doesn’t log me in from your link.

**Comment by roger88dc** [comment] 2018-11-25 21:54
under device preferences after I login I do have video sharing checked. is that what you were trying to get me to see? also with the pc app desktop the shows have downloaded and transferred to my pc desktop. so I assume the sharing setting is correct.

**Comment by mackworth** [comment] 2018-11-25 22:06
Sorry; I didn't read far enough into the log; it does show you changed that setting. 

In cTiVo's Preferences>General, is "Disable Sleep during downloads" on?  It really needs to be.

**Comment by roger88dc** [comment] 2018-11-25 22:06
yes, video sharing & enable video downloads are both checked. 
Also I never saw any warnings about forbidden access. 
should I uncheck then re-check sharing & enable video download boxes? or does that take 24 hrs to make a difference?

**Comment by roger88dc** [comment] 2018-11-25 22:09
disable was unchecked, I checked it, should I also check add to iTunes?

**Comment by mackworth** [comment] 2018-11-25 22:15
That's up to you. If you track your videos in iTunes and/or want them loaded onto the iPhone/iPad, then Yes.  You'll need to check if iTunes is set to "Copy files to iTunes Media folder when adding to library" is set in Advanced Preferences. If so, then you'll want to also check "Delete file after copying into iTunes", or you'll have two copies on your machine. Finally, if you want it to automatically sync your videos on to your iPhone, then check that last box, and set iTunes to automatically copy all unwatched videos onto your phone.

Try a few more now and let me know how they go.

**Comment by roger88dc** [comment] 2018-11-25 22:18
thanks
I actually don't need it in iTunes, I just thought it would be interesting to see if it went there but not the bottom pane for downloads. it should say complete I assume there when its on the Mac? and ready means it has been seen & waiting for d/l?

**Comment by roger88dc** [comment] 2018-11-25 22:33
ok
still progressing on DL stage. it has done that before though.
will let you know..

just curious, should be able to click on the top window and play on Mac from the existing show on the tivo to "watch it" or only after it has been d/l can it appear on my Mac

**Comment by mackworth** [comment] 2018-11-25 22:48
No, the only way to watch a show on the Mac is to first download and then watch it.  After it's complete, you should be able to right-click (Cmd-click) and "Play Video".  

On the other hand, you can tell the TiVo to play a show (on its connected TV) from the Mac (right-click-Play on TiVo)

**Comment by roger88dc** [comment] 2018-11-26 03:14
Well Hugh I wanted to try more than one file before I said all good.
Well, all is good. Thanks for your help today.
Roger

**Comment by mackworth** [comment] 2018-11-26 03:57
Good to hear. 

And @JimCarr-CM I take it you’re good too.

**Closed by mackworth** 2018-11-26 03:57 UTC
